#!/usr/bin/env perl

use strict;
use warnings;
use FindBin qw($Bin);
use MIME::Base64 qw(encode_base64);
use File::Spec;

my $root = File::Spec->catdir($Bin, '..');
my $input = File::Spec->catfile($root, 'docs', 'layout-templates-v1.json');
my $output = File::Spec->catfile(
    $root,
    'Albumzh.swiftpm',
    'Sources',
    'AlbumPhotoCore',
    'BuiltInLayoutTemplateCatalog.generated.swift'
);

open my $input_handle, '<:raw', $input
    or die "Impossible de lire $input: $!\n";
local $/;
my $manifest = <$input_handle>;
close $input_handle;

my $encoded = encode_base64($manifest, "\n");

open my $output_handle, '>:raw', $output
    or die "Impossible d'écrire $output: $!\n";
print {$output_handle} <<"SWIFT";
// Generated by tools/generate_layout_template_catalog.pl.
// Do not edit manually; docs/layout-templates-v1.json is the canonical source.

import Foundation

public struct LayoutTemplateManifest: Codable, Sendable, Equatable {
    public struct CanonicalPage: Codable, Sendable, Equatable {
        public let width: Int
        public let height: Int
    }

    public let manifestVersion: Int
    public let modelGeneration: String
    public let canonicalPage: CanonicalPage
    public let templates: [LayoutTemplateDefinition]
}

public enum BuiltInLayoutTemplateCatalog {
    private static let encodedManifest = """
$encoded"""

    public static let manifestData: Data = {
        guard let data = Data(
            base64Encoded: encodedManifest,
            options: .ignoreUnknownCharacters
        ) else {
            preconditionFailure("Manifeste de mises en page embarqué illisible")
        }
        return data
    }()

    public static let manifest: LayoutTemplateManifest = {
        do {
            let value = try JSONDecoder().decode(
                LayoutTemplateManifest.self,
                from: manifestData
            )
            guard value.manifestVersion == 1,
                  value.modelGeneration == AlbumModelVersion.generation,
                  value.canonicalPage.width == Int(AlbumPhotoConstants.canonicalPageWidth),
                  value.canonicalPage.height == Int(AlbumPhotoConstants.canonicalPageHeight) else {
                preconditionFailure("Contrat du manifeste de mises en page incompatible")
            }
            try LayoutTemplateEngine.validateCatalog(value.templates)
            return value
        } catch {
            preconditionFailure("Manifeste de mises en page embarqué invalide: \(error)")
        }
    }()

    public static var all: [LayoutTemplateDefinition] {
        manifest.templates
    }

    public static var active: [LayoutTemplateDefinition] {
        manifest.templates.filter(\\.isActive)
    }

    public static func template(
        id: String,
        version: Int
    ) -> LayoutTemplateDefinition? {
        manifest.templates.first { template in
            template.id == id && template.version == version
        }
    }
}
SWIFT
close $output_handle;

print "$output\n";
